# What a dev shell must actually DELIVER, as an executable both shells carry:
# `devenv test` runs it (that is devenv's whole `enterTest`), and the flake
# shell answers to `nix develop -c wowdps-dev-contract`.
#
# It tests the ENVIRONMENT, never the code: "evaluation didn't crash" is not
# the same claim as "cargo, the nightly toolchain, libduckdb and the GUI's
# dlopen path are all really here". A check kept beside one of two twin shells
# could only ever vouch for that one, which is why it lives here instead.
{
  pkgs,
  lib ? pkgs.lib,
  # The wrapper names, passed in from nix/dev/wrappers.nix so this list is
  # generated by the same thing that builds them.
  commands,
  # The pinned PKG_CONFIG_PATH, the sccache wrapper and devenv's linker
  # (env.nix): a shell that does not export exactly these has drifted from
  # its twin, and drift costs a rebuild on every switch.
  pinned,
  rustcWrapper,
  rustLinker,
  rustLinkerVar,
}:
pkgs.writeShellScriptBin "wowdps-dev-contract" (
  ''
    set -euo pipefail
    for tool in cargo rustc clippy-driver rustfmt rust-analyzer cargo-llvm-cov gawk okf coderabbit sccache \
                ${lib.concatStringsSep " " commands}; do
      command -v "$tool" > /dev/null || {
        echo "dev shell contract: $tool missing from PATH" >&2
        exit 1
      }
    done
    [ "''${RUSTC_WRAPPER:-}" = ${lib.escapeShellArg rustcWrapper} ] || {
      echo "dev shell contract: RUSTC_WRAPPER is ''${RUSTC_WRAPPER:-unset}, not sccache" >&2
      exit 1
    }
    case "$(rustc --version)" in
      *nightly*) ;;
      *) echo "dev shell contract: rustc is not the nightly rust-toolchain.toml names" >&2; exit 1 ;;
    esac
    # cargo-llvm-cov's llvm-cov / llvm-profdata: the toolchain's own
    # llvm-tools component, under the sysroot.
    for tool in llvm-cov llvm-profdata; do
      ls "$(rustc --print sysroot)"/lib/rustlib/*/bin/"$tool" > /dev/null 2>&1 || {
        echo "dev shell contract: $tool missing from the toolchain sysroot" >&2
        exit 1
      }
    done
  ''
  + lib.optionalString pkgs.stdenv.hostPlatform.isLinux ''
    # The twins hand cargo the same inputs (env.nix), or every switch
    # between the shells is a full rebuild: the pinned PKG_CONFIG_PATH (a
    # Linux pin: it lists the GUI's Linux libraries), and what devenv's
    # languages.rust adds, which the flake shell mirrors — its linker, and
    # the clang that sets CC and CXX. In devenv the linker check compares
    # the mirror's path against devenv's own.
    [ "''${PKG_CONFIG_PATH:-}" = ${lib.escapeShellArg pinned.PKG_CONFIG_PATH} ] || {
      echo "dev shell contract: PKG_CONFIG_PATH is not the pinned list (nix/dev/env.nix)" >&2
      exit 1
    }
    [ "''${${rustLinkerVar}:-}" = ${lib.escapeShellArg "${rustLinker}"} ] || {
      echo "dev shell contract: ${rustLinkerVar} is ''${${rustLinkerVar}:-unset}, not ${rustLinker}" >&2
      exit 1
    }
    [ "''${CC:-}" = clang ] && [ "''${CXX:-}" = clang++ ] || {
      echo "dev shell contract: CC/CXX are ''${CC:-unset}/''${CXX:-unset}, not clang/clang++" >&2
      exit 1
    }
    # xkbcommon, fontconfig and xcb: what the GUI's GPUI links.
    for pc in xkbcommon fontconfig xcb; do
      pkg-config --exists "$pc" || {
        echo "dev shell contract: $pc not visible to pkg-config" >&2
        exit 1
      }
    done
    [ -e "$DUCKDB_LIB_DIR/libduckdb.so" ] && [ -e "$DUCKDB_INCLUDE_DIR/duckdb.h" ] || {
      echo "dev shell contract: DUCKDB_LIB_DIR / DUCKDB_INCLUDE_DIR do not point at libduckdb" >&2
      exit 1
    }
    for so in libwayland-client.so libxkbcommon.so libvulkan.so libGL.so libduckdb.so; do
      found=0
      IFS=: read -ra dirs <<< "$LD_LIBRARY_PATH"
      for dir in "''${dirs[@]}"; do
        [ -e "$dir/$so" ] && found=1 && break
      done
      [ "$found" = 1 ] || {
        echo "dev shell contract: $so not on LD_LIBRARY_PATH" >&2
        exit 1
      }
    done
    echo "dev shell contract: ok"
  ''
)
