# What a dev shell must actually DELIVER, as an executable both shells carry:
# `devenv test` runs it (that is devenv's whole `enterTest`), and the flake
# shell answers to `nix develop -c wowdps-dev-contract`.
#
# It tests the ENVIRONMENT, never the code: "evaluation didn't crash" is not
# the same claim as "cargo, the nightly toolchain, libduckdb and the GUI's
# dlopen path are all really here". A check kept beside one of two twin shells
# could only ever vouch for that one, which is why it lives here instead.
{
  pkgs,
  lib ? pkgs.lib,
  # The wrapper names, passed in from nix/dev/wrappers.nix so this list is
  # generated by the same thing that builds them.
  commands,
}:
pkgs.writeShellScriptBin "wowdps-dev-contract" (
  ''
    set -euo pipefail
    for tool in cargo rustc clippy-driver rustfmt rust-analyzer cargo-llvm-cov gawk okf \
                ${lib.concatStringsSep " " commands}; do
      command -v "$tool" > /dev/null || {
        echo "dev shell contract: $tool missing from PATH" >&2
        exit 1
      }
    done
    case "$(rustc --version)" in
      *nightly*) ;;
      *) echo "dev shell contract: rustc is not the nightly rust-toolchain.toml names" >&2; exit 1 ;;
    esac
    # cargo-llvm-cov's llvm-cov / llvm-profdata: the toolchain's own
    # llvm-tools component, under the sysroot.
    for tool in llvm-cov llvm-profdata; do
      ls "$(rustc --print sysroot)"/lib/rustlib/*/bin/"$tool" > /dev/null 2>&1 || {
        echo "dev shell contract: $tool missing from the toolchain sysroot" >&2
        exit 1
      }
    done
  ''
  + lib.optionalString pkgs.stdenv.isLinux ''
    pkg-config --exists xkbcommon || {
      echo "dev shell contract: libxkbcommon not visible to pkg-config" >&2
      exit 1
    }
    [ -e "$DUCKDB_LIB_DIR/libduckdb.so" ] && [ -e "$DUCKDB_INCLUDE_DIR/duckdb.h" ] || {
      echo "dev shell contract: DUCKDB_LIB_DIR / DUCKDB_INCLUDE_DIR do not point at libduckdb" >&2
      exit 1
    }
    for so in libwayland-client.so libxkbcommon.so libvulkan.so libGL.so libduckdb.so; do
      found=0
      IFS=: read -ra dirs <<< "$LD_LIBRARY_PATH"
      for dir in "''${dirs[@]}"; do
        [ -e "$dir/$so" ] && found=1 && break
      done
      [ "$found" = 1 ] || {
        echo "dev shell contract: $so not on LD_LIBRARY_PATH" >&2
        exit 1
      }
    done
    echo "dev shell contract: ok"
  ''
)
