//! GENERATED by tools/gen-placed-spells.sh â do not edit by hand.
//! Source: local client DB2s via wowdps-extract, build 12.1.0.69933.
//! 33 placed spells.
//!
//! The spells that place something in the room, by spell id: how the
//! log tells where each stands, how it is drawn, its reach and how
//! long it stands (`super::Placed`). Membership is curated in
//! tools/extract/src/placegen.rs; every name, reach and duration is
//! the client's (or marked as by hand), and the real-log census
//! behind each entry sits in placed_spells.expected.md.

use super::Form::{Area, Gate, Post, Ring};
use super::Found::{Caster, Target, Thrown, Touch, Trips, Unit};
use super::Placed;
use super::Purpose::{Control, Heal, Wall, Way};

/// Sorted by spell id.
#[rustfmt::skip]
pub(super) static TABLE: &[Placed] = &[
    Placed { spell: 2484, name: "Earthbind Totem", purpose: Control, found: &[Unit], form: Area, reach: 10.0, lasts_ms: 20000, cooldown_ms: 30000, until_touched: false },
    Placed { spell: 5394, name: "Healing Stream Totem", purpose: Heal, found: &[Unit, Caster], form: Post, reach: 0.0, lasts_ms: 15000, cooldown_ms: 30000, until_touched: false },
    Placed { spell: 8143, name: "Tremor Totem", purpose: Heal, found: &[Unit, Caster], form: Post, reach: 0.0, lasts_ms: 10000, cooldown_ms: 60000, until_touched: false },
    Placed { spell: 30283, name: "Shadowfury", purpose: Control, found: &[Touch(&[30283])], form: Area, reach: 8.0, lasts_ms: 0, cooldown_ms: 60000, until_touched: false },
    Placed { spell: 48018, name: "Demonic Circle", purpose: Way, found: &[Caster], form: Post, reach: 0.0, lasts_ms: 900000, cooldown_ms: 10000, until_touched: false },
    Placed { spell: 51052, name: "Anti-Magic Zone", purpose: Wall, found: &[Touch(&[145629])], form: Area, reach: 8.0, lasts_ms: 6000, cooldown_ms: 240000, until_touched: false },
    Placed { spell: 51485, name: "Earthgrab Totem", purpose: Control, found: &[Unit], form: Area, reach: 8.0, lasts_ms: 20000, cooldown_ms: 30000, until_touched: false },
    Placed { spell: 62618, name: "Power Word: Barrier", purpose: Wall, found: &[Touch(&[81782])], form: Area, reach: 8.0, lasts_ms: 10000, cooldown_ms: 180000, until_touched: false },
    Placed { spell: 78675, name: "Solar Beam", purpose: Control, found: &[Target], form: Area, reach: 5.0, lasts_ms: 8000, cooldown_ms: 60000, until_touched: false },
    Placed { spell: 98008, name: "Spirit Link Totem", purpose: Wall, found: &[Unit], form: Area, reach: 10.0, lasts_ms: 6000, cooldown_ms: 180000, until_touched: false },
    Placed { spell: 101643, name: "Transcendence", purpose: Way, found: &[Unit, Caster], form: Post, reach: 0.0, lasts_ms: 900000, cooldown_ms: 10000, until_touched: false },
    Placed { spell: 102793, name: "Ursol's Vortex", purpose: Control, found: &[Touch(&[127797])], form: Area, reach: 8.0, lasts_ms: 10000, cooldown_ms: 60000, until_touched: false },
    Placed { spell: 108199, name: "Gorefiend's Grasp", purpose: Control, found: &[Target], form: Area, reach: 15.0, lasts_ms: 0, cooldown_ms: 90000, until_touched: false },
    Placed { spell: 108280, name: "Healing Tide Totem", purpose: Heal, found: &[Unit, Caster], form: Post, reach: 0.0, lasts_ms: 10000, cooldown_ms: 180000, until_touched: false },
    Placed { spell: 109248, name: "Binding Shot", purpose: Control, found: &[Touch(&[117405])], form: Area, reach: 5.0, lasts_ms: 10000, cooldown_ms: 45000, until_touched: false },
    Placed { spell: 111771, name: "Demonic Gateway", purpose: Way, found: &[Caster, Trips(113942)], form: Gate, reach: 0.0, lasts_ms: 900000, cooldown_ms: 10000, until_touched: false },
    Placed { spell: 113724, name: "Ring of Frost", purpose: Control, found: &[Unit, Touch(&[82691])], form: Ring, reach: 8.0, lasts_ms: 10000, cooldown_ms: 45000, until_touched: false },
    Placed { spell: 115313, name: "Summon Jade Serpent Statue", purpose: Heal, found: &[Unit], form: Post, reach: 0.0, lasts_ms: 900000, cooldown_ms: 10000, until_touched: false },
    Placed { spell: 115315, name: "Summon Black Ox Statue", purpose: Heal, found: &[Unit], form: Post, reach: 0.0, lasts_ms: 900000, cooldown_ms: 10000, until_touched: false },
    Placed { spell: 116844, name: "Ring of Peace", purpose: Control, found: &[Thrown], form: Area, reach: 8.0, lasts_ms: 5000, cooldown_ms: 45000, until_touched: false },
    Placed { spell: 121536, name: "Angelic Feather", purpose: Way, found: &[Touch(&[121557])], form: Post, reach: 2.0, lasts_ms: 15000, cooldown_ms: 20000, until_touched: true },
    Placed { spell: 145205, name: "Efflorescence", purpose: Heal, found: &[Unit, Touch(&[81269])], form: Area, reach: 10.0, lasts_ms: 30000, cooldown_ms: 0, until_touched: false },
    Placed { spell: 187650, name: "Freezing Trap", purpose: Control, found: &[Touch(&[3355])], form: Area, reach: 3.0, lasts_ms: 60000, cooldown_ms: 30000, until_touched: true },
    Placed { spell: 192058, name: "Capacitor Totem", purpose: Control, found: &[Unit], form: Area, reach: 8.0, lasts_ms: 3000, cooldown_ms: 60000, until_touched: false },
    Placed { spell: 192077, name: "Wind Rush Totem", purpose: Way, found: &[Unit, Touch(&[192082])], form: Area, reach: 10.0, lasts_ms: 15000, cooldown_ms: 120000, until_touched: false },
    Placed { spell: 196718, name: "Darkness", purpose: Wall, found: &[Caster], form: Area, reach: 8.0, lasts_ms: 8000, cooldown_ms: 300000, until_touched: false },
    Placed { spell: 202137, name: "Sigil of Silence", purpose: Control, found: &[Touch(&[204490])], form: Area, reach: 8.0, lasts_ms: 2000, cooldown_ms: 90000, until_touched: false },
    Placed { spell: 202138, name: "Sigil of Chains", purpose: Control, found: &[Touch(&[204843])], form: Area, reach: 8.0, lasts_ms: 2000, cooldown_ms: 60000, until_touched: false },
    Placed { spell: 207684, name: "Sigil of Misery", purpose: Control, found: &[Touch(&[207685])], form: Area, reach: 8.0, lasts_ms: 2000, cooldown_ms: 120000, until_touched: false },
    Placed { spell: 383013, name: "Poison Cleansing Totem", purpose: Heal, found: &[Unit, Caster], form: Post, reach: 0.0, lasts_ms: 6000, cooldown_ms: 120000, until_touched: false },
    Placed { spell: 444995, name: "Surging Totem", purpose: Heal, found: &[Unit, Touch(&[73921])], form: Area, reach: 10.0, lasts_ms: 25000, cooldown_ms: 25000, until_touched: false },
    Placed { spell: 1232285, name: "Efflorescence", purpose: Heal, found: &[Unit, Touch(&[81269])], form: Area, reach: 10.0, lasts_ms: 30000, cooldown_ms: 0, until_touched: false },
    Placed { spell: 1267068, name: "Stormstream Totem", purpose: Heal, found: &[Unit, Caster], form: Post, reach: 0.0, lasts_ms: 15000, cooldown_ms: 30000, until_touched: false },
];
