#!/usr/bin/env python3
"""Regenerate crates/core/src/keystone_timers.rs from wago.tools DB2 exports.

Dev-time only — the output is committed so builds never touch the network.
Run once per game patch (par times are retuned between seasons):

    python3 tools/gen-keystone-timers.py            # latest live build
    python3 tools/gen-keystone-timers.py --build 12.1.0.68914
    python3 tools/gen-keystone-timers.py --cache /tmp/db2   # reuse downloads

Source: MapChallengeMode.db2 — one row per keystone dungeon, keyed by the
challengeID that CHALLENGE_MODE_START carries in field 3. CriteriaCount_0/1/2
are the par / +2 / +3 timers in seconds. The +2/+3 thresholds are NOT always
80%/60% of par (legacy challenge modes use gold/silver/bronze times, and a
few modern rows deviate), so all three are emitted.
"""
import argparse
import csv
import datetime
import io
import json
import os
import sys
import urllib.request

WAGO = "https://wago.tools"


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": "wowdps-gen-keystone-timers"})
    with urllib.request.urlopen(req, timeout=120) as r:
        return r.read()


def latest_build():
    builds = json.loads(fetch(f"{WAGO}/api/builds"))
    for product in ("wow", "wow_classic_era", "wowt"):
        if builds.get(product):
            return builds[product][0]["version"]
    sys.exit("no build found in wago.tools /api/builds")


def load_table(name, build, cache_dir):
    path = os.path.join(cache_dir, f"{name}-{build}.csv") if cache_dir else None
    if path and os.path.exists(path):
        data = open(path, "rb").read()
    else:
        data = fetch(f"{WAGO}/db2/{name}/csv?build={build}")
        if path:
            os.makedirs(cache_dir, exist_ok=True)
            with open(path, "wb") as f:
                f.write(data)
    return list(csv.DictReader(io.StringIO(data.decode("utf-8"))))


def emit(rows, build, out_path):
    entries = []
    for r in rows:
        cid = int(r["ID"])
        par_s = int(r["CriteriaCount_0"])
        plus2_s = int(r["CriteriaCount_1"])
        plus3_s = int(r["CriteriaCount_2"])
        if par_s <= 0:
            continue
        if not plus3_s <= plus2_s <= par_s:
            sys.exit(f"row {cid}: timers not descending: {par_s} {plus2_s} {plus3_s}")
        entries.append((cid, par_s * 1000, plus2_s * 1000, plus3_s * 1000, r["Name_lang"]))
    entries.sort()
    today = datetime.date.today().isoformat()
    with open(out_path, "w") as f:
        f.write(
            f"""//! GENERATED by tools/gen-keystone-timers.py — do not edit by hand.
//! Source: wago.tools MapChallengeMode.db2, build {build}, generated {today}.
//! {len(entries)} dungeons.
//!
//! Keystone timers per dungeon, keyed by CHALLENGE_MODE_START's
//! challengeID (CONTRACT.md R10): (par, +2, +3) in milliseconds. A run at
//! or under par is timed (and earns the tier its clock beats); over it is
//! depleted. The combat log's END success flag only means "completed", so
//! the timed verdict needs this table.

/// A keystone dungeon's (par, +2, +3) timers, in milliseconds.
pub(crate) fn pars_ms(challenge_id: u32) -> Option<(i64, i64, i64)> {{
    let i = TABLE.binary_search_by_key(&challenge_id, |e| e.0).ok()?;
    let (_, par, plus2, plus3) = TABLE[i];
    Some((par, plus2, plus3))
}}

#[rustfmt::skip]
static TABLE: [(u32, i64, i64, i64); {len(entries)}] = [
"""
        )
        for cid, par_ms, plus2_ms, plus3_ms, name in entries:
            f.write(f"    ({cid}, {par_ms}, {plus2_ms}, {plus3_ms}), // {name}\n")
        f.write(
            """];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn table_is_sorted_by_challenge_id() {
        assert!(TABLE.windows(2).all(|w| w[0].0 < w[1].0));
    }

    #[test]
    fn timers_are_plausible_and_descending() {
        // Pars between 10 minutes and 2 hours (legacy challenge modes reach
        // 85:00), +3 <= +2 <= par — a tripwire against the DB2 columns
        // changing meaning under us.
        assert!(TABLE.iter().all(|e| (600_000..7_200_000).contains(&e.1)));
        assert!(TABLE.iter().all(|e| e.3 <= e.2 && e.2 <= e.1));
    }
}
"""
        )
    print(f"{out_path}: {len(entries)} dungeons, build {build}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--build")
    ap.add_argument("--cache")
    args = ap.parse_args()
    build = args.build or latest_build()
    rows = load_table("MapChallengeMode", build, args.cache)
    out = os.path.join(
        os.path.dirname(__file__), "..", "crates", "core", "src", "keystone_timers.rs"
    )
    emit(rows, build, os.path.normpath(out))


if __name__ == "__main__":
    main()
