//! The `crates/core/src/keystone_timers.rs` generator: a Rust port of the
//! retired `tools/gen-keystone-timers.py`, consuming MapChallengeMode.db2
//! (now decoded from the local install instead of downloaded from
//! wago.tools) and emitting a byte-identical body, so regenerating on an
//! unchanged build is a no-op. Run once per game patch — par times are
//! retuned between seasons.
//!
//! One row per keystone dungeon, keyed by the challengeID that
//! CHALLENGE_MODE_START carries in field 3. CriteriaCount_0/1/2 are the
//! par / +2 / +3 timers in seconds. The +2/+3 thresholds are NOT always
//! 80%/60% of par (legacy challenge modes use gold/silver/bronze times,
//! and a few modern rows deviate), so all three are emitted.

use crate::table::Csv;
use std::fmt::Write as _;

/// The source table with its FileDataID (from wowdev/wow-listfile).
pub const TABLE: (&str, u32) = ("MapChallengeMode", 801709);

#[derive(Debug)]
pub struct Generated {
    pub content: String,
    pub dungeons: usize,
}

pub fn generate(csv: &Csv, build: &str) -> Result<Generated, String> {
    let id_c = csv.col("ID")?;
    let par_c = csv.col("CriteriaCount_0")?;
    let plus2_c = csv.col("CriteriaCount_1")?;
    let plus3_c = csv.col("CriteriaCount_2")?;
    let name_c = csv.col("Name_lang")?;

    let cell = |r: &[String], c: usize| -> Result<i64, String> {
        r[c].parse()
            .map_err(|_| format!("bad numeric cell {:?}", r[c]))
    };

    let mut entries: Vec<(u32, i64, i64, i64, String)> = Vec::new();
    for r in &csv.rows {
        let cid = cell(r, id_c)? as u32;
        let par_s = cell(r, par_c)?;
        let plus2_s = cell(r, plus2_c)?;
        let plus3_s = cell(r, plus3_c)?;
        if par_s <= 0 {
            continue;
        }
        if !(plus3_s <= plus2_s && plus2_s <= par_s) {
            return Err(format!(
                "row {cid}: timers not descending: {par_s} {plus2_s} {plus3_s}"
            ));
        }
        entries.push((
            cid,
            par_s * 1000,
            plus2_s * 1000,
            plus3_s * 1000,
            r[name_c].clone(),
        ));
    }
    entries.sort();

    let mut o = String::new();
    o.push_str("//! GENERATED by tools/gen-keystone-timers.sh — do not edit by hand.\n");
    // No timestamp: same build in, same bytes out.
    writeln!(
        o,
        "//! Source: local client MapChallengeMode.db2 via wowdps-extract, build {build}."
    )
    .unwrap();
    writeln!(o, "//! {} dungeons.", entries.len()).unwrap();
    o.push_str(
        "//!\n\
         //! Keystone timers per dungeon, keyed by CHALLENGE_MODE_START's\n\
         //! challengeID (CONTRACT.md R10): (par, +2, +3) in milliseconds. A run at\n\
         //! or under par is timed (and earns the tier its clock beats); over it is\n\
         //! depleted. The combat log's END success flag only means \"completed\", so\n\
         //! the timed verdict needs this table.\n\
         \n\
         /// A keystone dungeon's (par, +2, +3) timers, in milliseconds.\n\
         pub(crate) fn pars_ms(challenge_id: u32) -> Option<(i64, i64, i64)> {\n\
         \x20   let i = TABLE.binary_search_by_key(&challenge_id, |e| e.0).ok()?;\n\
         \x20   let (_, par, plus2, plus3) = TABLE[i];\n\
         \x20   Some((par, plus2, plus3))\n\
         }\n\
         \n\
         #[rustfmt::skip]\n",
    );
    writeln!(
        o,
        "static TABLE: [(u32, i64, i64, i64); {}] = [",
        entries.len()
    )
    .unwrap();
    for (cid, par_ms, plus2_ms, plus3_ms, name) in &entries {
        writeln!(
            o,
            "    ({cid}, {par_ms}, {plus2_ms}, {plus3_ms}), // {name}"
        )
        .unwrap();
    }
    o.push_str(
        "];\n\
         \n\
         #[cfg(test)]\n\
         mod tests {\n\
         \x20   use super::*;\n\
         \n\
         \x20   #[test]\n\
         \x20   fn table_is_sorted_by_challenge_id() {\n\
         \x20       assert!(TABLE.windows(2).all(|w| w[0].0 < w[1].0));\n\
         \x20   }\n\
         \n\
         \x20   #[test]\n\
         \x20   fn timers_are_plausible_and_descending() {\n\
         \x20       // Pars between 10 minutes and 2 hours (legacy challenge modes reach\n\
         \x20       // 85:00), +3 <= +2 <= par — a tripwire against the DB2 columns\n\
         \x20       // changing meaning under us.\n\
         \x20       assert!(TABLE.iter().all(|e| (600_000..7_200_000).contains(&e.1)));\n\
         \x20       assert!(TABLE.iter().all(|e| e.3 <= e.2 && e.2 <= e.1));\n\
         \x20   }\n\
         }\n",
    );

    Ok(Generated {
        content: o,
        dungeons: entries.len(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::table::parse_csv;

    const HEADER: &str = "ID,CriteriaCount_0,CriteriaCount_1,CriteriaCount_2,Name_lang\n";

    #[test]
    fn emits_sorted_ms_table() {
        let csv = parse_csv(&format!(
            "{HEADER}9,2700,2160,1620,Dungeon B\n2,1800,1440,1080,Dungeon A\n5,0,0,0,Unused\n"
        ))
        .unwrap();
        let g = generate(&csv, "1.2.3.4").unwrap();
        assert_eq!(g.dungeons, 2);
        assert!(g.content.contains("build 1.2.3.4"));
        assert!(g.content.contains("//! 2 dungeons."));
        assert!(
            g.content
                .contains("static TABLE: [(u32, i64, i64, i64); 2] = [\n")
        );
        // Sorted by challenge id, seconds scaled to ms, name comments kept;
        // the par-0 row is dropped.
        assert!(g.content.contains(
            "    (2, 1800000, 1440000, 1080000), // Dungeon A\n    (9, 2700000, 2160000, 1620000), // Dungeon B\n"
        ));
        assert!(!g.content.contains("Unused"));
    }

    #[test]
    fn non_descending_timers_fail_loudly() {
        let csv = parse_csv(&format!("{HEADER}3,1800,1900,1080,Broken\n")).unwrap();
        let err = generate(&csv, "1.2.3.4").unwrap_err();
        assert!(err.contains("timers not descending"), "{err}");
    }
}
