//! The `crates/core/src/open_world_maps.rs` generator, consuming Map.db2
//! from the local install. Run once per game patch — a new expansion's
//! continents arrive with it.
//!
//! One entry per map whose InstanceType is 0: the open world. A ZONE_CHANGE
//! carries the instance's map id (Map.db2's ID) and a difficulty, and the
//! game sometimes stamps a door OUT of an instance with the difficulty it
//! just left (`ZONE_CHANGE,0,"Silvermoon City",15` on a hearth out of a
//! Heroic raid, `ZONE_CHANGE,2444,"The Waking Shores",8` after a key). R10
//! reads a nonzero difficulty as zoned in, so such a door opened a visit in
//! a city. This table lets the meter and the scanner tell an open-world map
//! from an instance; a map the table does not know (a newer patch) keeps the
//! old reading, its difficulty.

use crate::table::Csv;
use std::fmt::Write as _;

/// The source table with its FileDataID (from wowdev/wow-listfile).
pub const TABLE: (&str, u32) = ("Map", 1349477);

#[derive(Debug)]
pub struct Generated {
    pub content: String,
    pub maps: usize,
}

pub fn generate(csv: &Csv, build: &str) -> Result<Generated, String> {
    let id_c = csv.col("ID")?;
    let type_c = csv.col("InstanceType")?;
    let name_c = csv.col("MapName_lang")?;

    // The column indexes come from `Csv::col`, so a miss means the row
    // itself is short — a malformed table, not a bug here.
    let text = |r: &[String], c: usize| -> Result<String, String> {
        r.get(c)
            .cloned()
            .ok_or_else(|| format!("Map: row has no column {c}"))
    };
    let cell = |r: &[String], c: usize| -> Result<i64, String> {
        let v = text(r, c)?;
        v.parse()
            .map_err(|_| format!("Map: bad numeric cell {v:?}"))
    };

    let mut entries: Vec<(u32, String)> = Vec::new();
    for r in &csv.rows {
        let id = cell(r, id_c)?;
        let kind = cell(r, type_c)?;
        // 0 open world, 1 party, 2 raid, 3 pvp, 4 arena, 5 scenario and a
        // few newer kinds past it; anything outside a byte means the column
        // moved under us.
        if !(0..=255).contains(&kind) {
            return Err(format!("map {id}: InstanceType {kind} out of range"));
        }
        if kind == 0 {
            let id = u32::try_from(id).map_err(|_| format!("map id {id} out of range"))?;
            // A name's newlines or comment markers would break the emitted
            // line comment.
            let name = text(r, name_c)?.replace(['\n', '\r'], " ");
            entries.push((id, name));
        }
    }
    entries.sort();
    if entries.is_empty() {
        return Err("Map: no open-world rows — the table or its schema changed".into());
    }

    let mut o = String::new();
    o.push_str("//! GENERATED by tools/gen-open-world-maps.sh — do not edit by hand.\n");
    // No timestamp: same build in, same bytes out.
    writeln!(
        o,
        "//! Source: local client Map.db2 via wowdps-extract, build {build}."
    )
    .map_err(|e| format!("emit: {e}"))?;
    writeln!(o, "//! {} open-world maps.", entries.len()).map_err(|e| format!("emit: {e}"))?;
    o.push_str(
        "//!\n\
         //! Every map whose InstanceType is 0 (CONTRACT.md R10): a door onto one\n\
         //! is zoned out whatever difficulty it carries, because the game stamps\n\
         //! a door out of an instance with the difficulty it just left. A map\n\
         //! this table does not know keeps the door's difficulty.\n\
         \n\
         /// Is `map_id` (a ZONE_CHANGE's or an ENCOUNTER_START's instance id)\n\
         /// open world?\n\
         pub(crate) fn open_world(map_id: u32) -> bool {\n\
         \x20   TABLE.binary_search(&map_id).is_ok()\n\
         }\n\
         \n\
         #[rustfmt::skip]\n",
    );
    writeln!(o, "static TABLE: [u32; {}] = [", entries.len()).map_err(|e| format!("emit: {e}"))?;
    for (id, name) in &entries {
        writeln!(o, "    {id}, // {name}").map_err(|e| format!("emit: {e}"))?;
    }
    o.push_str(
        "];\n\
         \n\
         #[cfg(test)]\n\
         mod tests {\n\
         \x20   use super::*;\n\
         \n\
         \x20   #[test]\n\
         \x20   fn table_is_sorted_by_map_id() {\n\
         \x20       assert!(TABLE.windows(2).all(|w| w[0] < w[1]));\n\
         \x20   }\n\
         \n\
         \x20   #[test]\n\
         \x20   fn continents_are_open_world_and_instances_are_not() {\n\
         \x20       // Eastern Kingdoms (Silvermoon's map) and Kalimdor are open\n\
         \x20       // world; a tripwire against the column changing meaning.\n\
         \x20       assert!(open_world(0) && open_world(1));\n\
         \x20       assert!(!TABLE.contains(&u32::MAX));\n\
         \x20   }\n\
         }\n",
    );

    Ok(Generated {
        content: o,
        maps: entries.len(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::table::parse_csv;

    const HEADER: &str = "ID,MapName_lang,InstanceType\n";

    #[test]
    fn emits_the_sorted_open_world_maps_alone() {
        let csv = parse_csv(&format!(
            "{HEADER}2444,Dragon Isles,0\n3004,The Venomous Abyss,2\n0,Eastern Kingdoms,0\n2953,Parhelion Plaza,5\n"
        ))
        .unwrap();
        let g = generate(&csv, "1.2.3.4").unwrap();
        assert_eq!(g.maps, 2);
        assert!(g.content.contains("build 1.2.3.4"));
        assert!(g.content.contains("//! 2 open-world maps."));
        assert!(g.content.contains("static TABLE: [u32; 2] = [\n"));
        assert!(
            g.content
                .contains("    0, // Eastern Kingdoms\n    2444, // Dragon Isles\n")
        );
        assert!(!g.content.contains("Venomous"));
        assert!(!g.content.contains("Parhelion"));
    }

    #[test]
    fn a_nonsense_instance_type_fails_loudly() {
        let csv = parse_csv(&format!("{HEADER}7,Broken,4096\n")).unwrap();
        let err = generate(&csv, "1.2.3.4").unwrap_err();
        assert!(err.contains("out of range"), "{err}");
    }
}
