//! What players place in the room, which the replay draws: totems, a
//! warlock's gates, rings, zones, statues, sigils and traps. For each
//! spell that places one, how the log tells where it stands (`Found`),
//! how it is drawn (`Form`), its reach and how long it stands.
//!
//! The table (`placed_spells.rs`) is GENERATED by tools/gen-placed-spells.sh
//! from a list curated in tools/extract/src/placegen.rs: the client's
//! tables prove each entry's name and give its reach and duration, and a
//! census of real logs (tools/placed-spells-census.csv) shows the log
//! writing every spell an entry names. The cut (`cut-pull`) keeps the lines
//! of these spells, and the replay reads them through this table.

mod placed_spells;

/// How the log tells where a placed spell stands. An entry lists what
/// tells, most trusted first; the replay takes the first that does.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Found {
    /// The unit its summon made, wherever the log posts it: a totem's own
    /// casts carry its position, so a totem moved is seen moved.
    Unit,
    /// Where the units these spells reached stood when they did: an aura
    /// put on them, or a heal or a hit landing on them.
    Touch(&'static [u32]),
    /// Where its caster stood as it was cast.
    Caster,
    /// Where the unit its cast was aimed at stood.
    Target,
    /// A Demonic Gateway's far gate: where the travelers this aura marks
    /// (once a trip) leave from or land, the near gate being where its
    /// caster stood.
    Trips(u32),
    /// Where the enemies it threw out of it were thrown from (Ring of
    /// Peace, whose log line is its cast alone).
    Thrown,
}

/// What a placed spell is for: how it matters in a fight, and how loudly
/// the replay draws it.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Purpose {
    /// A way across the room: a gateway, a speed totem, a feather, a
    /// circle or spirit to come back to.
    Way,
    /// Crowd control: a ring, a sigil, a trap, a stun or grip.
    Control,
    /// A raid's wall against damage: a barrier, a zone, Spirit Link.
    Wall,
    /// Healing where it stands: a healing totem, a carpet, a statue.
    Heal,
}

/// How a placed spell is drawn.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Form {
    /// An area: its reach as a disc round where it stands.
    Area,
    /// A ring: its reach as the ring's line (Ring of Frost, whose middle
    /// is no part of it).
    Ring,
    /// Two gates and the way between them (Demonic Gateway).
    Gate,
    /// A thing standing at a point, whatever reaches it (a statue, a
    /// healing totem, a circle to come back to).
    Post,
}

/// A spell that places something in the room.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Placed {
    /// The spell a player casts to place it: the summon's own, for a
    /// summoned unit (the log's SPELL_SUMMON names it).
    pub spell: u32,
    pub name: &'static str,
    pub purpose: Purpose,
    /// What tells where it stands, most trusted first.
    pub found: &'static [Found],
    pub form: Form,
    /// Its reach in yards; 0 where none is drawn.
    pub reach: f32,
    /// How long it stands from its cast, in ms; 0 for one that is gone as
    /// it lands (drawn as a flash).
    pub lasts_ms: u32,
    /// How long its caster waits to place it again (ms): its cooldown, or its
    /// charges' recharge, from the client, before talents.
    pub cooldown_ms: u32,
    /// Whether it stands only until the first unit it touches (a trap, a
    /// feather), `lasts_ms` at most.
    pub until_touched: bool,
}

impl Placed {
    /// Every spell id the log may tell where it stands by: its `Touch` and
    /// `Trips` spells.
    pub fn telling(&self) -> impl Iterator<Item = u32> + '_ {
        self.found.iter().flat_map(|f| match f {
            Found::Touch(ids) => ids.to_vec(),
            Found::Trips(id) => vec![*id],
            _ => Vec::new(),
        })
    }
}

/// Every placed spell, by spell id.
pub fn all() -> &'static [Placed] {
    placed_spells::TABLE
}

/// The placed spell a cast or summon of `spell` makes, if any.
pub fn placed(spell: u32) -> Option<&'static Placed> {
    let table = placed_spells::TABLE;
    table
        .binary_search_by_key(&spell, |p| p.spell)
        .ok()
        .and_then(|i| table.get(i))
}

/// Whether `spell` tells where some placed spell stands (a `Touch` or
/// `Trips` spell of any entry).
pub fn tells(spell: u32) -> bool {
    all().iter().any(|p| p.telling().any(|id| id == spell))
}
