//! GENERATED by tools/gen-keystone-timers.sh — do not edit by hand.
//! Source: local client MapChallengeMode.db2 via wowdps-extract, build 12.0.7.68974.
//! 82 dungeons.
//!
//! Keystone timers per dungeon, keyed by CHALLENGE_MODE_START's
//! challengeID (CONTRACT.md R10): (par, +2, +3) in milliseconds. A run at
//! or under par is timed (and earns the tier its clock beats); over it is
//! depleted. The combat log's END success flag only means "completed", so
//! the timed verdict needs this table.

/// A keystone dungeon's (par, +2, +3) timers, in milliseconds.
pub(crate) fn pars_ms(challenge_id: u32) -> Option<(i64, i64, i64)> {
    let i = TABLE.binary_search_by_key(&challenge_id, |e| e.0).ok()?;
    let &(_, par, plus2, plus3) = TABLE.get(i)?;
    Some((par, plus2, plus3))
}

#[rustfmt::skip]
static TABLE: [(u32, i64, i64, i64); 82] = [
    (2, 1800000, 1440000, 1080000), // Temple of the Jade Serpent
    (56, 2700000, 1260000, 720000), // Stormstout Brewery
    (57, 2700000, 1320000, 780000), // Gate of the Setting Sun
    (58, 3600000, 2100000, 1260000), // Shado-Pan Monastery
    (59, 3000000, 1800000, 1050000), // Siege of Niuzao Temple
    (60, 2700000, 1440000, 720000), // Mogu'shan Palace
    (76, 3300000, 1980000, 1140000), // Scholomance
    (77, 2700000, 1320000, 780000), // Scarlet Halls
    (78, 2700000, 1320000, 780000), // Scarlet Monastery
    (161, 1680000, 1344000, 1008000), // Skyreach
    (163, 1800000, 1440000, 1080000), // Bloodmaul Slag Mines
    (164, 3300000, 1920000, 1140000), // Auchindoun
    (165, 1980000, 1584000, 1188000), // Shadowmoon Burial Grounds
    (166, 1800000, 1440000, 1080000), // Grimrail Depot
    (167, 5100000, 2580000, 1500000), // Upper Blackrock Spire
    (168, 1980000, 1584000, 1188000), // The Everbloom
    (169, 1800000, 1440000, 1080000), // Iron Docks
    (197, 2100000, 1680000, 1260000), // Eye of Azshara
    (198, 1800000, 1440000, 1080000), // Darkheart Thicket
    (199, 2160000, 1728000, 1296000), // Black Rook Hold
    (200, 2280000, 1824000, 1368000), // Halls of Valor
    (206, 1980000, 1584000, 1188000), // Neltharion's Lair
    (207, 1980000, 1584000, 1188000), // Vault of the Wardens
    (208, 1440000, 1152000, 864000), // Maw of Souls
    (209, 2700000, 2160000, 1620000), // The Arcway
    (210, 1800000, 1440000, 1080000), // Court of Stars
    (227, 2520000, 2016000, 1512000), // Return to Karazhan: Lower
    (233, 2100000, 1680000, 1260000), // Cathedral of Eternal Night
    (234, 2100000, 1680000, 1260000), // Return to Karazhan: Upper
    (239, 2040000, 1632000, 1224000), // Seat of the Triumvirate
    (244, 1800000, 1440000, 1080000), // Atal'Dazar
    (245, 1800000, 1440000, 1080000), // Freehold
    (246, 2160000, 1728000, 1296000), // Tol Dagor
    (247, 1980000, 1584000, 1188000), // The MOTHERLODE!!
    (248, 2220000, 1776000, 1332000), // Waycrest Manor
    (249, 2520000, 2016000, 1512000), // Kings' Rest
    (250, 2160000, 1728000, 1296000), // Temple of Sethraliss
    (251, 1800000, 1440000, 1080000), // The Underrot
    (252, 2520000, 2016000, 1512000), // Shrine of the Storm
    (353, 1980000, 1584000, 1188000), // Siege of Boralus
    (369, 2280000, 1824000, 1368000), // Operation: Mechagon - Junkyard
    (370, 1920000, 1536000, 1118000), // Operation: Mechagon - Workshop
    (375, 1800000, 1440000, 1080000), // Mists of Tirna Scithe
    (376, 1860000, 1488000, 1116000), // The Necrotic Wake
    (377, 2580000, 2064000, 1548000), // De Other Side
    (378, 1920000, 1536000, 1152000), // Halls of Atonement
    (379, 2280000, 1824000, 1368000), // Plaguefall
    (380, 2460000, 1968000, 1476000), // Sanguine Depths
    (381, 2340000, 1872000, 1404000), // Spires of Ascension
    (382, 2040000, 1632000, 1224000), // Theater of Pain
    (391, 2100000, 1680000, 1260000), // Tazavesh: Streets of Wonder
    (392, 1800000, 1440000, 1080000), // Tazavesh: So'leah's Gambit
    (399, 1800000, 1440000, 1080000), // Ruby Life Pools
    (400, 2400000, 1920000, 1440000), // The Nokhud Offensive
    (401, 2250000, 1800000, 1350000), // The Azure Vault
    (402, 1860000, 1488000, 1116000), // Algeth'ar Academy
    (403, 2100000, 1680000, 1260000), // Uldaman: Legacy of Tyr
    (404, 1980000, 1584000, 1188000), // Neltharus
    (405, 2100000, 1680000, 1260000), // Brackenhide Hollow
    (406, 2100000, 1680000, 1260000), // Halls of Infusion
    (438, 1800000, 1440000, 1080000), // The Vortex Pinnacle
    (456, 2040000, 1632000, 1224000), // Throne of the Tides
    (463, 2040000, 1632000, 1224000), // Dawn of the Infinite: Galakrond's Fall
    (464, 2160000, 1728000, 1296000), // Dawn of the Infinite: Murozond's Rise
    (499, 1950000, 1560000, 1170000), // Priory of the Sacred Flame
    (500, 1740000, 1392000, 1044000), // The Rookery
    (501, 1980000, 1584000, 1188000), // The Stonevault
    (502, 2100000, 1680000, 1260000), // City of Threads
    (503, 1800000, 1440000, 1080000), // Ara-Kara, City of Echoes
    (504, 1860000, 1488000, 1116000), // Darkflame Cleft
    (505, 1860000, 1488000, 1116000), // The Dawnbreaker
    (506, 1980000, 1584000, 1188000), // Cinderbrew Meadery
    (507, 2040000, 1632000, 1224000), // Grim Batol
    (525, 1980000, 1584000, 1188000), // Operation: Floodgate
    (541, 1800000, 1440000, 1080000), // The Stonecore
    (542, 1860000, 1488000, 1116000), // Eco-Dome Al'dani
    (556, 1800000, 1440000, 1080000), // Pit of Saron
    (557, 1980000, 1584000, 1188000), // Windrunner Spire
    (558, 2040000, 1632000, 1224000), // Magisters' Terrace
    (559, 1800000, 1440000, 1080000), // Nexus-Point Xenas
    (560, 1980000, 1584000, 1188000), // Maisara Caverns
    (583, 1200000, 1200000, 1200000), // Seat of the Triumvirate
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn table_is_sorted_by_challenge_id() {
        assert!(TABLE.windows(2).all(|w| w[0].0 < w[1].0));
    }

    #[test]
    fn timers_are_plausible_and_descending() {
        // Pars between 10 minutes and 2 hours (legacy challenge modes reach
        // 85:00), +3 <= +2 <= par — a tripwire against the DB2 columns
        // changing meaning under us.
        assert!(TABLE.iter().all(|e| (600_000..7_200_000).contains(&e.1)));
        assert!(TABLE.iter().all(|e| e.3 <= e.2 && e.2 <= e.1));
    }
}
