//! GENERATED by tools/gen-keystone-timers.sh — do not edit by hand.
//! Source: local client MapChallengeMode.db2 via wowdps-extract, build 12.1.0.69933.
//! 87 dungeons.
//!
//! Keystone timers per dungeon, keyed by CHALLENGE_MODE_START's
//! challengeID (CONTRACT.md R10): (par, +2, +3) in milliseconds. A run at
//! or under par is timed (and earns the tier its clock beats); over it is
//! depleted. The combat log's END success flag only means "completed", so
//! the timed verdict needs this table.

/// A keystone dungeon's (par, +2, +3) timers, in milliseconds.
pub(crate) fn pars_ms(challenge_id: u32) -> Option<(i64, i64, i64)> {
    let i = TABLE.binary_search_by_key(&challenge_id, |e| e.0).ok()?;
    let &(_, _, par, plus2, plus3) = TABLE.get(i)?;
    Some((par, plus2, plus3))
}

/// The timers of the one keystone dungeon on `map_id` — what a key joined
/// mid-run gets, since its END carries the map and no challengeID. A map
/// holding two challenge modes (a split dungeon) is ambiguous: `None`.
pub(crate) fn pars_for_map(map_id: u32) -> Option<(i64, i64, i64)> {
    let mut on_map = TABLE.iter().filter(|e| e.1 == map_id);
    let &(_, _, par, plus2, plus3) = on_map.next()?;
    on_map.next().is_none().then_some((par, plus2, plus3))
}

#[rustfmt::skip]
static TABLE: [(u32, u32, i64, i64, i64); 87] = [
    (2, 960, 1800000, 1440000, 1080000), // Temple of the Jade Serpent
    (56, 961, 2700000, 1260000, 720000), // Stormstout Brewery
    (57, 962, 2700000, 1320000, 780000), // Gate of the Setting Sun
    (58, 959, 3600000, 2100000, 1260000), // Shado-Pan Monastery
    (59, 1011, 3000000, 1800000, 1050000), // Siege of Niuzao Temple
    (60, 994, 2700000, 1440000, 720000), // Mogu'shan Palace
    (76, 1007, 3300000, 1980000, 1140000), // Scholomance
    (77, 1001, 2700000, 1320000, 780000), // Scarlet Halls
    (78, 1004, 2700000, 1320000, 780000), // Scarlet Monastery
    (161, 1209, 1680000, 1344000, 1008000), // Skyreach
    (163, 1175, 1800000, 1440000, 1080000), // Bloodmaul Slag Mines
    (164, 1182, 3300000, 1920000, 1140000), // Auchindoun
    (165, 1176, 1980000, 1584000, 1188000), // Shadowmoon Burial Grounds
    (166, 1208, 1800000, 1440000, 1080000), // Grimrail Depot
    (167, 1358, 5100000, 2580000, 1500000), // Upper Blackrock Spire
    (168, 1279, 1980000, 1584000, 1188000), // The Everbloom
    (169, 1195, 1800000, 1440000, 1080000), // Iron Docks
    (197, 1456, 2100000, 1680000, 1260000), // Eye of Azshara
    (198, 1466, 1800000, 1440000, 1080000), // Darkheart Thicket
    (199, 1501, 2160000, 1728000, 1296000), // Black Rook Hold
    (200, 1477, 2280000, 1824000, 1368000), // Halls of Valor
    (206, 1458, 1980000, 1584000, 1188000), // Neltharion's Lair
    (207, 1493, 1980000, 1584000, 1188000), // Vault of the Wardens
    (208, 1492, 1440000, 1152000, 864000), // Maw of Souls
    (209, 1516, 2700000, 2160000, 1620000), // The Arcway
    (210, 1571, 1800000, 1440000, 1080000), // Court of Stars
    (227, 1651, 2520000, 2016000, 1512000), // Return to Karazhan: Lower
    (233, 1677, 2100000, 1680000, 1260000), // Cathedral of Eternal Night
    (234, 1651, 2100000, 1680000, 1260000), // Return to Karazhan: Upper
    (239, 1753, 2040000, 1632000, 1224000), // Seat of the Triumvirate
    (244, 1763, 1800000, 1440000, 1080000), // Atal'Dazar
    (245, 1754, 1800000, 1440000, 1080000), // Freehold
    (246, 1771, 2160000, 1728000, 1296000), // Tol Dagor
    (247, 1594, 1980000, 1584000, 1188000), // The MOTHERLODE!!
    (248, 1862, 2220000, 1776000, 1332000), // Waycrest Manor
    (249, 1762, 1980000, 1584000, 1188000), // Kings' Rest
    (250, 1877, 1920000, 1536000, 1152000), // Temple of Sethraliss
    (251, 1841, 1800000, 1440000, 1080000), // The Underrot
    (252, 1864, 2520000, 2016000, 1512000), // Shrine of the Storm
    (353, 1822, 1980000, 1584000, 1188000), // Siege of Boralus
    (369, 2097, 2280000, 1824000, 1368000), // Operation: Mechagon - Junkyard
    (370, 2097, 1920000, 1536000, 1118000), // Operation: Mechagon - Workshop
    (375, 2290, 1800000, 1440000, 1080000), // Mists of Tirna Scithe
    (376, 2286, 1860000, 1488000, 1116000), // The Necrotic Wake
    (377, 2291, 2580000, 2064000, 1548000), // De Other Side
    (378, 2287, 1920000, 1536000, 1152000), // Halls of Atonement
    (379, 2289, 2280000, 1824000, 1368000), // Plaguefall
    (380, 2284, 2460000, 1968000, 1476000), // Sanguine Depths
    (381, 2285, 2340000, 1872000, 1404000), // Spires of Ascension
    (382, 2293, 2040000, 1632000, 1224000), // Theater of Pain
    (391, 2441, 2100000, 1680000, 1260000), // Tazavesh: Streets of Wonder
    (392, 2441, 1800000, 1440000, 1080000), // Tazavesh: So'leah's Gambit
    (399, 2521, 1680000, 1344000, 1008000), // Ruby Life Pools
    (400, 2516, 2400000, 1920000, 1440000), // The Nokhud Offensive
    (401, 2515, 2250000, 1800000, 1350000), // The Azure Vault
    (402, 2526, 1860000, 1488000, 1116000), // Algeth'ar Academy
    (403, 2451, 2100000, 1680000, 1260000), // Uldaman: Legacy of Tyr
    (404, 2519, 1980000, 1584000, 1188000), // Neltharus
    (405, 2520, 2100000, 1680000, 1260000), // Brackenhide Hollow
    (406, 2527, 2100000, 1680000, 1260000), // Halls of Infusion
    (438, 657, 1800000, 1440000, 1080000), // The Vortex Pinnacle
    (456, 643, 2040000, 1632000, 1224000), // Throne of the Tides
    (463, 2579, 2040000, 1632000, 1224000), // Dawn of the Infinite: Galakrond's Fall
    (464, 2579, 2160000, 1728000, 1296000), // Dawn of the Infinite: Murozond's Rise
    (499, 2649, 1950000, 1560000, 1170000), // Priory of the Sacred Flame
    (500, 2648, 1740000, 1392000, 1044000), // The Rookery
    (501, 2652, 1980000, 1584000, 1188000), // The Stonevault
    (502, 2669, 2100000, 1680000, 1260000), // City of Threads
    (503, 2660, 1800000, 1440000, 1080000), // Ara-Kara, City of Echoes
    (504, 2651, 1860000, 1488000, 1116000), // Darkflame Cleft
    (505, 2662, 1860000, 1488000, 1116000), // The Dawnbreaker
    (506, 2661, 1980000, 1584000, 1188000), // Cinderbrew Meadery
    (507, 670, 2040000, 1632000, 1224000), // Grim Batol
    (525, 2773, 1980000, 1584000, 1188000), // Operation: Floodgate
    (541, 725, 1800000, 1440000, 1080000), // The Stonecore
    (542, 2830, 1860000, 1488000, 1116000), // Eco-Dome Al'dani
    (556, 658, 1800000, 1440000, 1080000), // Pit of Saron
    (557, 2805, 1980000, 1584000, 1188000), // Windrunner Spire
    (558, 2811, 2040000, 1632000, 1224000), // Magisters' Terrace
    (559, 2915, 1800000, 1440000, 1080000), // Nexus-Point Xenas
    (560, 2874, 1980000, 1584000, 1188000), // Maisara Caverns
    (583, 1753, 1200000, 1200000, 1200000), // Seat of the Triumvirate
    (584, 2859, 1800000, 1440000, 1080000), // The Blinding Vale
    (585, 2923, 1800000, 1440000, 1080000), // Voidscar Arena
    (586, 2825, 1920000, 1536000, 1152000), // Den of Nalorakk
    (587, 2813, 2040000, 1632000, 1224000), // Murder Row
    (588, 2993, 1800000, 1440000, 1080000), // Altar of Fangs
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn table_is_sorted_by_challenge_id() {
        assert!(TABLE.windows(2).all(|w| w[0].0 < w[1].0));
    }

    #[test]
    fn timers_are_plausible_and_descending() {
        // Pars between 10 minutes and 2 hours (legacy challenge modes reach
        // 85:00), +3 <= +2 <= par — a tripwire against the DB2 columns
        // changing meaning under us.
        assert!(TABLE.iter().all(|e| (600_000..7_200_000).contains(&e.2)));
        assert!(TABLE.iter().all(|e| e.4 <= e.3 && e.3 <= e.2));
    }

    #[test]
    fn a_map_finds_its_one_dungeon_and_a_split_map_finds_none() {
        for e in TABLE.iter() {
            let twins = TABLE.iter().filter(|o| o.1 == e.1).count();
            let want = (twins == 1).then_some((e.2, e.3, e.4));
            assert_eq!(pars_for_map(e.1), want, "map {}", e.1);
        }
        assert_eq!(pars_for_map(0), None);
    }
}
