//! GENERATED by tools/gen-open-world-maps.sh — do not edit by hand.
//! Source: local client Map.db2 via wowdps-extract, build 12.1.0.69933.
//! 589 open-world maps.
//!
//! Every map whose InstanceType is 0 (CONTRACT.md R10): a door onto one
//! is zoned out whatever difficulty it carries, because the game stamps
//! a door out of an instance with the difficulty it just left. A map
//! this table does not know keeps the door's difficulty.

/// Is `map_id` (a ZONE_CHANGE's or an ENCOUNTER_START's instance id)
/// open world?
pub(crate) fn open_world(map_id: u32) -> bool {
    TABLE.binary_search(&map_id).is_ok()
}

#[rustfmt::skip]
static TABLE: [u32; 589] = [
    0, // Eastern Kingdoms
    1, // Kalimdor
    369, // Deeprun Tram
    449, // Alliance PVP Barracks
    450, // Horde PVP Barracks
    530, // Outland
    571, // Northrend
    582, // Transport: Rut'theran to Auberdine
    584, // Transport: Menethil to Theramore
    586, // Transport: Exodar to Auberdine
    587, // Transport: Feathermoon Ferry
    588, // Transport: Menethil to Auberdine
    589, // Transport: Orgrimmar to Grom'Gol
    590, // Transport: Grom'Gol to Undercity
    591, // Transport: Undercity to Orgrimmar
    592, // Transport: Borean Tundra Test
    593, // Transport: Booty Bay to Ratchet
    594, // Transport: Howling Fjord Sister Mercy (Quest)
    596, // Transport: Naglfar
    609, // Ebon Hold
    610, // Transport: Tirisfal to Vengeance Landing
    612, // Transport: Menethil to Valgarde
    613, // Transport: Orgrimmar to Warsong Hold
    614, // Transport: Stormwind to Valiance Keep
    620, // Transport: Moa'ki to Unu'pe
    621, // Transport: Moa'ki to Kamagua
    622, // Transport: Orgrim's Hammer
    623, // Transport: The Skybreaker
    638, // Gilneas
    641, // Transport: Alliance Airship BG
    642, // Transport: HordeAirshipBG
    646, // Deepholm
    647, // Transport: Orgrimmar to Thunder Bluff
    648, // LostIsles
    654, // Gilneas2
    655, // GilneasPhase1
    656, // GilneasPhase2
    659, // Lost Isles Volcano Eruption
    661, // Lost Isles Town in a Box
    662, // Transport: Alliance Vashj'ir Ship
    672, // Transport: The Skybreaker (Icecrown Citadel Raid)
    673, // Transport: Orgrim's Hammer (Icecrown Citadel Raid)
    674, // Transport: Ship to Vashj'ir
    712, // Transport: The Skybreaker (IC Dungeon)
    713, // Transport: Orgrim's Hammer (IC Dungeon)
    718, // Transport: The Mighty Wind (Icecrown Citadel Raid)
    719, // Mount Hyjal Phase 1
    723, // Stormwind
    730, // Maelstrom Zone
    731, // Stonetalon Bomb
    732, // Tol Barad
    736, // Twilight Highlands Dragonmaw Phase
    738, // Ship to Vashj'ir (Orgrimmar -> Vashj'ir)
    739, // Vashj'ir Sub - Horde
    740, // Vashj'ir Sub - Alliance
    741, // Twilight Highlands Horde Transport
    742, // Vashj'ir Sub - Horde - Circling Abyssal Maw
    743, // Vashj'ir Sub - Alliance circling Abyssal Maw
    746, // Uldum Phase Oasis
    747, // Transport: Deepholm Gunship
    748, // Transport: Onyxia/Nefarian Elevator
    749, // Transport: Gilneas Moving Gunship
    750, // Transport: Gilneas Static Gunship
    751, // Redridge - Orc Bomb
    752, // Redridge - Bridge Phase One
    753, // Redridge - Bridge Phase Two
    759, // Uldum Phased Entrance
    760, // Twilight Highlands Phased Entrance
    762, // Twilight Highlands Zeppelin 1
    763, // Twilight Highlands Zeppelin 2
    764, // Uldum - Phase Wrecked Camp
    765, // Krazzworks Attack Zeppelin
    766, // Transport: Gilneas Moving Gunship 02
    767, // Transport: Gilneas Moving Gunship 03
    860, // The Wandering Isle
    861, // Molten Front
    870, // Pandaria
    971, // Jade Forest Alliance Hub Phase
    972, // Jade Forest Battlefield Phase
    974, // Darkmoon Faire
    975, // Turtle Ship Phase 01
    976, // Turtle Ship Phase 02
    1019, // Ruins of Theramore
    1043, // Brawl'gar Arena
    1061, // Horde Beach Daily Area
    1062, // Alliance Beach Daily Area
    1064, // Mogu Island Daily Area
    1066, // Stormwind Gunship Pandaria Start Area
    1074, // Orgrimmar Gunship Pandaria Start
    1075, // Theramore's Fall Phase
    1076, // Jade Forest Horde Starting Area
    1101, // Defense Of The Ale House BG
    1106, // Jaina Dalaran Scenario
    1107, // Dreadscar Rift
    1113, // Transport: DarkmoonCarousel
    1116, // Draenor
    1120, // Thunder King Horde Hub
    1121, // Thunder Island Alliance Hub
    1128, // Mogu Island Events - Horde Base
    1129, // Mogu Island Events - Alliance Base
    1132, // Transport: The Skybag (Brawl'gar Arena)
    1133, // Transport: Zandalari Ship (Mogu Island)
    1172, // Transport: Siege of Orgrimmar (Alliance)
    1173, // Transport: Siege of Orgrimmar (Horde)
    1179, // Warcraft Heroes
    1181, // PattyMack Test Garrison Bldg Map
    1190, // Blasted Lands Phase
    1192, // Transport: Gorgrond Train
    1212, // Garrison - Alliance - Blacksmith 3
    1213, // Garrison - Alliance - Alchemy 1
    1214, // Garrison - Alliance - Enchanting 3
    1215, // Garrison - Alliance - Engineering 3
    1216, // Garrison - Alliance - Farm1
    1217, // Garrison - Alliance - Inscription 1
    1218, // Garrison - Alliance - Jewelcrafting 1
    1219, // Garrison - Alliance - Leatherworking 1
    1220, // Broken Isles
    1221, // Garrison - Alliance Mine 1
    1222, // Garrison - Alliance Mine 2
    1223, // Garrison - Alliance Mine 3
    1224, // Garrison - Alliance Stable 1
    1225, // Garrison - Alliance Stable 2
    1226, // Garrison - Alliance Stable 3
    1227, // Garrison - Alliance - Tailoring 3
    1229, // Garrison - Alliance - Inn 1
    1230, // Garrison - Alliance - Barn 1
    1231, // Transport: Wavemurder Barge
    1247, // Garrison - Alliance - Armory 1
    1248, // Garrison - Alliance - Barracks 1
    1249, // Garrison - Alliance - Engineering 1
    1250, // Alliance - Garrison - Herb Garden 1 (UNUSED)
    1251, // Alliance - Garrison - Inn 1 DONT USE
    1252, // Garrison - Alliance - Lumbermill 1
    1253, // Garrison - Alliance - Mage Tower 1
    1254, // Garrison - Alliance - Sparring Arena 1
    1255, // Garrison - Alliance - Salvage Yard 1
    1256, // Garrison - Alliance - StoreHouse 1
    1257, // Garrison - Alliance - Trading Post 1
    1258, // Garrison - Alliance - Tailoring 1
    1259, // Garrison - Alliance - Enchanting 1
    1260, // Garrison - Alliance - Blacksmith 1
    1261, // Garrison - Alliance - Plot Small
    1262, // Garrison - Allilance - Plot Medium
    1263, // Garrison - Alliance - Plot Large
    1265, // Tanaan Jungle Intro
    1273, // Nagrand - Garrison Camp - Stable2
    1278, // Garrison - Horde - Barracks 1
    1281, // Garrison - Horde - Alchemy 1
    1282, // Garrison - Horde - Armory 1
    1283, // Garrison - Horde - Barn 1
    1284, // Garrison - Horde - Blacksmith 1
    1285, // Garrison - Horde - Enchanting 1
    1286, // Garrison - Horde - Engineering 1
    1287, // Garrison - Horde - Inn 1
    1288, // Garrison - Horde - Inscription 1
    1289, // Garrison - Horde - Jewelcrafting 1
    1290, // Garrison - Horde - Leatherworking 1
    1291, // Garrison - Horde - Lumbermill 1
    1292, // Garrison - Horde - Mage Tower 1
    1293, // Garrison - Horde - Mine 1
    1294, // Garrison - Horde - Pet Stable 1
    1295, // Garrison - Horde - Salvage Yard 1
    1296, // Garrison - Horde - Sparring Arena 1
    1297, // Garrison - Horde - Stable 1
    1298, // Garrison - Horde Storehouse 1
    1299, // Garrison - Horde - Tailoring 1
    1300, // Garrison - Horde - Trading Post 1
    1301, // Garrison - Horde - Workshop 1
    1302, // Garrison - Alliance - Workshop 1
    1303, // Garrison - Horde - Farm1
    1304, // Garrison - Horde - Plot Large
    1305, // Garrison - Horde - Plot Medium
    1306, // Garrison - Horde - Plot Small
    1307, // Tanaan Jungle Intro - Forge Phase
    1308, // Garrison - Horde - Fishing 1
    1309, // Garrison - Alliance - Fishing 1
    1311, // Outdoor Garrison - Arena - Horde (NEEDS WMO)
    1312, // Outdoor Garrison - Arena - Alliance (NEEDS WMO)
    1313, // Outdoor Garrison - Lumber Mill - Alliance
    1314, // Outdoor Garrison - Lumber Mill - Horde
    1315, // Outdoor Garrison - Armory - Horde
    1316, // Outdoor Garrison - Armory - Alliance
    1317, // Outdoor Garrison - Mage Tower - Horde
    1318, // Outdoor Garrison - Mage Tower - Alliance
    1319, // Outdoor Garrison - Stables - Horde
    1320, // Outdoor Garrison - Stables - Alliance
    1321, // Outdoor Garrison - Workshop - Horde
    1322, // Outdoor Garrison - Workshop - Alliance
    1323, // Outdoor Garrison - Inn - Horde
    1324, // Outdoor Garrison - Inn - Alliance
    1325, // Outdoor Garrison - Tradiing Post 1 - Horde
    1326, // Outdoor Garrison - Tradiing Post - Alliance
    1327, // Outdoor Garrison - Construction Plot, Medium - Horde
    1328, // Outdoor Garrison - Construction Plot, Medium - Alliance
    1332, // Garrison - Horde - Barracks 2
    1333, // Garrison - Horde - Armory 2
    1334, // Garrison - Horde - Barn 2
    1335, // Garrison - Horde - Inn 2
    1336, // Garrison - Horde - Lumbermill 2
    1337, // Garrison - Horde - Mage Tower 2
    1338, // Garrison - Horde - Pet Stable 2
    1339, // Garrison - Horde - Stable 2
    1340, // Garrison - Horde - Trading Post 2
    1341, // Garrison - Horde - Workshop 2
    1342, // Garrison - Horde - Barracks 3
    1343, // Garrison - Horde - Armory 3
    1344, // Garrison - Horde - Barn 3
    1345, // Garrison - Horde - Inn 3
    1346, // Garrison - Horde - Mage Tower 3
    1347, // Garrison - Horde - Pet Stable 3
    1348, // Garrison - Horde - Stable 3
    1349, // Garrison - Horde - Trading Post 3
    1350, // Garrison - Horde - Workshop 3
    1351, // Garrison - Alliance - Large - Construction
    1352, // Garrison - Alliance - Medium - Construction
    1353, // Garrison - Horde - Large - Construction
    1354, // Garrison - Horde - Medium - Construction
    1361, // Garrison - Alliance - Mage Tower 2
    1362, // Garrison - Alliance - Mage Tower 3
    1363, // Garrison - Horde - Mine 2
    1364, // Garrison - Horde - Mine 3
    1367, // Garrison - Alliance - Workshop 2
    1368, // Garrison - Alliance - Workshop 3
    1369, // Garrison - Alliance - Lumbermill 2
    1370, // Garrison - Alliance - Lumbermill 3
    1371, // Garrison - Horde - Small - Construction
    1372, // Garrison - Alliance - Small - Construction
    1375, // Garrison - Alliance - Alchemy 2
    1376, // Garrison - Alliance - Alchemy 3
    1377, // Garrison - Alliance - Blacksmith 2
    1378, // Garrison - Alliance - Enchanting 2
    1379, // Garrison - Alliance - Engineering 2
    1380, // Garrison - Alliance - Inscription 2
    1381, // Garrison - Alliance - Inscription 3
    1382, // Garrison - Alliance - Jewelcrafting 2
    1383, // Garrison - Alliance - Jewelcrafting 3
    1384, // Garrison - Alliance - Leatherworking 2
    1385, // Garrison - Alliance - Leatherworking 3
    1386, // Garrison - Alliance - Tailoring 2
    1387, // Garrison - Alliance - StoreHouse 2
    1388, // Garrison - Alliance - StoreHouse 3
    1389, // Garrison - Horde Storehouse 2
    1390, // Garrison - Horde Storehouse 3
    1391, // Garrison - Alliance - Salvage Yard 2
    1392, // Garrison - Alliance - Salvage Yard 3
    1393, // Garrison - Horde - Lumbermill 3
    1394, // Garrison - Alliance - Sparring Arena 2
    1395, // Garrison - Alliance - Sparring Arena 3
    1396, // Garrison - Alliance - Trading Post 2
    1397, // Garrison - Alliance - Trading Post 3
    1398, // Garrison - Alliance - Barn 2
    1399, // Garrison - Alliance - Barn 3
    1400, // Garrison - Alliance - Inn 2
    1401, // Garrison - Alliance - Inn 3
    1403, // Garrison - Alliance - Barracks 2
    1404, // Garrison - Alliance - Barracks 3
    1405, // Garrison - Alliance - Armory 2
    1406, // Garrison - Alliance - Armory 3
    1409, // Garrison - Horde - Sparring Arena 2
    1410, // Garrison - Horde - Sparring Arena 3
    1411, // Garrison - Horde - Alchemy 2
    1412, // Garrison - Horde - Alchemy 3
    1413, // Garrison - Horde - Blacksmith 2
    1414, // Garrison - Horde - Blacksmith 3
    1415, // Garrison - Horde - Enchanting 2
    1416, // Garrison - Horde - Enchanting 3
    1417, // Garrison - Horde - Inscription 2
    1418, // Garrison - Horde - Inscription 3
    1419, // Garrison - Horde - Leatherworking 2
    1420, // Garrison - Horde - Leatherworking 3
    1421, // Garrison - Horde - Jewelcrafting 2
    1422, // Garrison - Horde - Jewelcrafting 3
    1423, // Garrison - Horde - Tailoring 2
    1424, // Garrison - Horde - Tailoring 3
    1425, // Garrison - Horde - Salvage Yard 2
    1426, // Garrison - Horde - Salvage Yard 3
    1427, // PattyMack Test Garrison Bld Map2
    1429, // Garrison - Horde - Engineering 2
    1430, // Garrison - Horde - Engineering 3
    1432, // Garrison - Horde - Fishing 2
    1433, // Garrison - Horde - Fishing 3
    1434, // Garrison - Alliance - Fishing 2
    1435, // Garrison - Alliance - Fishing 3
    1437, // Garrison - Alliance - Pet Stable 1
    1438, // Garrison - Alliance - Pet Stable 2
    1439, // Garrison - Alliance - Pet Stable 3
    1440, // Garrison - Alliance - Infirmary 1
    1441, // Garrison - Alliance - Infirmary 2
    1442, // Garrison - Alliance - Infirmary 3
    1446, // Outdoor Garrison - Construction Plot, Large - Alliance
    1447, // Outdoor Garrison - Construction Plot, Large - Horde
    1459, // Transport: The Iron Mountain
    1462, // Illidans Rock
    1463, // Helhiem Exterior Area
    1464, // Tanaan Jungle
    1465, // Tanaan Jungle - No Hubs Phase
    1468, // Warden Prison DH Quests
    1469, // The Heart of Azeroth
    1471, // Dungeon Test Map 1466
    1473, // Garrison - Alliance - Shipyard
    1474, // Garrison - Horde - Shipyard
    1476, // Transport: The Maw of Nashal
    1479, // Skyhold
    1481, // Mardum
    1482, // Garrison Shipyard - Submarine - Alliance
    1483, // Garrison Shipyard - Destroyer - Alliance
    1484, // Garrison Shipyard - Transport
    1485, // Garrison Shipyard - Battleship - Alliance
    1486, // Garrison Shipyard - Carrier - Horde
    1487, // Garrison Shipyard - Submarine - Horde
    1488, // Garrison Shipyard - Destroyer - Horde
    1496, // Garrison Shipyard - Carrier - Alliance
    1497, // Garrison Shipyard - Battleship - Horde
    1502, // Dalaran Underbelly
    1509, // Bloodtotem Cavern - Fel Phase
    1510, // Bloodtotem Cavern - Tauren Phase
    1512, // Netherlight Temple
    1513, // Hall of the Guardian
    1514, // The Wandering Isle
    1515, // Huln's War
    1517, // Stormheim Prescenario Windrunner
    1518, // Stormheim Prescenario Skyfire
    1519, // The Fel Hammer
    1527, // High Mountain Scenario
    1532, // High Mountain Mesa Scenario
    1538, // test
    1540, // Emerald Dreamway
    1547, // Artifact - Combat - Acquisition Ship
    1555, // zzOLD - Transport: Boost Experience - Alliance Gunship
    1556, // zzOLD - Transport: Boost Experience - Horde Gunship
    1559, // 7.0 Transport: Boost Experience - Horde Gunship
    1560, // 7.0 Transport: Boost Experience - Alliance Gunship
    1586, // Assault on Stormwind
    1602, // Artifact - The Vortex Pinnacle - Shaman Order Hall
    1604, // Artifact - Order Campaign - Portal World Niskara
    1605, // Firelands_Artifact
    1608, // Hyjal War of the Ancients Quest
    1618, // Death Knight Campaign - Scarlet Monastery
    1627, // Fel Hammer DH Scenario
    1628, // Transport: Alliance Battleship
    1637, // Transport: Alliance Ship PhaseableMO
    1638, // Transport: Horde Ship PhaseableMO
    1639, // Transport: Kvaldir Ship PhaseableMO
    1642, // Zandalar
    1643, // Kul Tiras
    1644, // Plunder Isle
    1647, // Vol'jin's Funeral Pyre
    1649, // Transport: Horde Battleship
    1650, // Legion Command Ship Transport
    1657, // zzOldBlade's Edge Arena
    1669, // Argus
    1670, // Broken Shore (Delete)
    1671, // Broken Shore - Prepatch 7.2 (Backup)
    1675, // Winter AB_old
    1678, // AB Phase 1
    1679, // AB Phase 2
    1680, // AB Phase 3
    1682, // The Fel Hammer Terrain Phase
    1692, // Pit of Saron - Death Knight Campaign
    1696, // Legion - Command Center
    1697, // Legion - Legion Spider Cave
    1699, // Legion - Legion Fel Cave
    1700, // Legion - Legion Fel Firenova Area
    1701, // Legion - Legion Barracks
    1711, // Alliance Submarine (7.1.5 Boat Holiday)
    1716, // Broken Shore Mage Tower
    1718, // Nazjatar
    1741, // The Vindicaar
    1750, // Azuremyst Isle
    1751, // Alliance Battleship (7.3 Intro)
    1752, // Sunstrider Battleship (7.3 Intro)
    1773, // Shadow of Azeroth
    1775, // Maw of N'Zoth
    1776, // Horde Battleship - The Banshee's Wail
    1779, // Invasion Points
    1785, // 8.0 Islands - Ship - Pirateship
    1786, // 8.0 Islands - Zeppelin - Goblin
    1787, // 8.0 Islands - Micro - Mogu Crypt
    1795, // Vale of Eternal Blossoms
    1806, // Alliance Battleship -  Wind's Redemption
    1815, // Silithus Phase
    1817, // Silithus: The Wound
    1839, // Karazan Chess
    1844, // 8.0 Islands - Event
    1845, // 8.0 Islands - Event
    1846, // 8.0 Islands - Ship - 6HU Cargoship
    1850, // 8.2.5 - MSEM - 1850
    1851, // 8.0 Islands - Ship - 7FK Buccaneer
    1855, // The Vindicaar
    1856, // Transport: Azerite BG - Alliance Airship
    1857, // Transport: Azerite BG - Horde Gunship
    1860, // The Vindicaar
    1865, // Telogrus Rift
    1902, // Silithus Alliance Gunship
    1903, // Silithus Horde Gunship
    1909, // [UNUSED] Transport: Kul Tiras - Bridgeport
    1910, // Transport: Kul Tiras - Bridgeport - The Maiden's Virtue
    1913, // PhaseableMO: Nazmir - Triangulation Platform
    1916, // PhaseableMO: Nazmir - Ship World Quest
    1918, // Kalimdor Darkshore Phase
    1919, // 8.0 Islands - Platform - KL Skywall Entrance Building 03
    1920, // 8.0 Islands - Platform - MD Flamegate E
    1921, // 8.0 Islands - Ship - Player Alliance - Kul'Tiras Medium 01 With Gangplank
    1922, // 8.0 Islands - Ship - Player Horde - Zandalari Medium 01 With Gangplank
    1923, // 8.0 Islands - Platform - Deepholm Mercury Pool 01
    1924, // 8.0 Islands - Platform - 7AZ Vashjir Small Cave A
    1926, // 8.1.5 Allies - Kul Tiran Flagship (JAK)
    1927, // Zandalari Flagship
    1929, // Chamber of Heart
    1930, // Zandalar Alliance Intro Scenario
    1931, // Lordaeron Blight
    1935, // 8.0 Islands - Cave - 8KUL_CaveMicro01
    1936, // 8.0 Islands - Cave - 8KUL_CaveMicro02
    1937, // 8.0 Islands - Cave - 8KUL_CaveMicro03
    1938, // 8.0 Islands - Cave - 8RIV_CaveMicro_01
    1939, // 8.0 Islands - Cave - 8RIV_CaveMicro_02
    1940, // Alliance Battleship -  Wind's Redemption Voldun
    1941, // Transport: Nazmir Raid Elevator
    1942, // Molten Core
    1945, // Arathi Highlands 2
    1951, // 8.0 Transport: Boost Experience - Alliance Gunship
    1952, // 8.0 Transport: Boost Experience - Horde Gunship
    1953, // 8.0 Islands - Platform - demigod dome living
    1954, // The Great Sea Alliance
    1956, // 8.0 Islands - Platform - Hot Old God 03
    1957, // 8.0 Islands - Platform - Old God
    1958, // The Golden Skipper - Zandalari Transport Ship
    1959, // Zandalari Transport Ship Large
    1962, // Goblin Ship Final
    1964, // PhaseableMO: War Campaign - Horde - Chapter 05 - Kul Tiras Flagship
    1965, // PhaseableMO: War Campaign - Horde - Chapter 05 - Kul Tiras Ship
    2066, // The Great Sea Horde
    2067, // Zandalari Battleship - Gral's Call
    2069, // Zuldazar Alliance Bombing Run
    2074, // 8.0 Transport: Boralus to Stormwind
    2075, // 8.0 Islands - Event
    2077, // 8.0 Islands - Event
    2078, // 8.0 Islands - Event
    2081, // Blackrock Depths - Dark Iron Dwarf Hub
    2082, // 8.0 Islands - Micro - Mogu Crypt
    2083, // 8.0 Islands - Micro - Mogu Crypt
    2084, // 8.0 Islands - Micro - Mogu Crypt
    2085, // 8.0 Islands - Micro - Mogu Crypt
    2086, // 8.0 Islands - Micro - Mogu Crypt
    2087, // 8.0 Islands - Micro - Mogu Crypt
    2088, // 8.0 Islands - Micro - Mogu Crypt
    2094, // 8.0 Transport: Boralus Canals
    2095, // 8.0 Transport: Boralus Sound
    2101, // 8.0 Transport: Boralus Barge
    2102, // 8.0 Transport: Boralus Ship Small
    2103, // Darkshore Prepatch Darnassian Ship
    2109, // 8.1.0 Incursion Airship Horde
    2110, // 8.1.0 Incursion Airship Alliance
    2114, // Maw Prototype
    2119, // Transport: Cooking: Impossible - Hot Air Balloon - Alliance
    2120, // Transport: Cooking: Impossible - Hot Air Balloon - Horde
    2123, // Shrine of the Storm Quests
    2127, // Siren Isle
    2128, // Dagger Realm
    2129, // 8.1 Darkshore Horde Quests
    2131, // 8.1 Darkshore Outdoor Final Phase
    2136, // Transport: Zuldazar Raid Ship
    2145, // Transport: Night Elf Warship
    2146, // Transport: Forsaken Warship
    2147, // Icecrown Citadel (8.1)
    2160, // Maw Prototype - Dragonblight
    2165, // SpawnedMO: Night Elf Warship
    2166, // Transport: Zuldazar Raid Boralus Ship
    2175, // 9.0 NPE (New Player Experience) - Exile's Reach
    2176, // SpawnedMO: Forsaken Ship Large
    2186, // The Obsidian Sanctum - 8.2 Magni - Heart of Azeroth
    2194, // Hearthstone Tavern
    2195, // Arcantina
    2205, // 9.0 Transport: Zone Transition Test
    2215, // Chamber of Heart - Repaired
    2222, // The Shadowlands
    2237, // 8.2.5 Orgrimmar
    2241, // Uldum
    2246, // Solesa Naksu [DNT]
    2261, // 9.0 Transport - NPE - Alliance Battleship
    2263, // Crapopolis
    2267, // city
    2268, // Mechagon City
    2274, // Vision of the Twisting Sands
    2275, // Vale of Eternal Twilight
    2276, // 9.0 Transport - Maldraxxus Necropolis [Transport]
    2277, // 9.0 SpawnedMO - Maldraxxus Necropolis [WMO]
    2297, // Icecrown Citadel (8.3)
    2309, // Transport: Torghast Bridge Platform01 Elevator
    2355, // The Necrotic Wake (Transport)
    2364, // The Maw
    2365, // 9.0 Maw - Torghast - 9Maw_Bridge_SmallPlatform01
    2366, // 9.0 Maw - Torghast - 9Maw_Zone_WallTurret01
    2367, // 9.0 Maw - Torghast - 9Maw_Bridge_Straight03
    2368, // Maldraxxus Broker Islands
    2369, // 9.0 NPE - Horde - Starter Transport Ship - (STM)
    2370, // Maldraxxus Arena
    2374, // Zereth Mortis
    2439, // De Other Side (Ardenweald Campaign)
    2444, // Dragon Isles
    2453, // Torghast
    2454, // Zaralek Cavern
    2456, // The Maw
    2469, // Torghast
    2472, // Skyhold
    2482, // Font of Fealty
    2485, // Torghast
    2486, // Torghast
    2487, // Torghast
    2488, // Torghast
    2489, // Torghast
    2490, // Torghast
    2507, // Void Zone: Airship
    2512, // Grand Time Adventure
    2518, // Old Beyfir
    2523, // The Defiant Dragonscale
    2524, // The Rugged Dragonscale
    2529, // Young Belvo
    2532, // Ruins of Lordaeron
    2534, // 10.0 Dragon Isles -  Black Dragon Citadel - Narrative Version
    2548, // Emerald Dream
    2552, // Khaz Algar (Surface)
    2570, // 10.0 The Forbidden Reach (Child of 2444)
    2573, // Lost Arvillo
    2576, // Sully Test Space
    2601, // Khaz Algar
    2616, // Zskera Vaults
    2637, // Dragon Isles
    2666, // Amirdrassil
    2668, // 10.1.7 Tyr Scenario - Black Empire
    2671, // The Dawnbreaker
    2672, // The Dawnbreaker
    2673, // Ambush Airship A
    2674, // Ambush Airship B
    2676, // Ambush Airship C
    2677, // Ambush Airship D
    2678, // The Timeways (Dawn of the Infinite Outdoor)
    2694, // Harandar
    2698, // 11.0 - Chamber of Heart
    2703, // 11.0 Warband Screen
    2704, // 11.0 Warband Testing 2
    2706, // Undermine
    2708, // 10.2.5 Transport: Bel'ameth -> Gilneas
    2728, // 11.0.0 Transport: The Reckoning (Crashed Airship)
    2731, // 11.0 Dalaran Scenario
    2738, // K'aresh
    2739, // Hall of Awakening
    2760, // 11.0.0 Transport: Arathi Airship 1
    2761, // 11.0.0 Transport: Arathi Airship 2
    2762, // 11.0.0 Transport: Arathi Airship 3
    2763, // 11.0.0 Transport: Arathi Airship 4
    2764, // 11.0.0 Transport: Arathi Airship 5
    2771, // Voidstorm
    2780, // 11.0.0 Transport: Arathi Airship 7
    2782, // 11.0 - Vault of Memory
    2785, // Dragon Isles
    2786, // Pocket Dimension
    2794, // 11.2.7 - The Wandering Isle
    2796, // Arathi Highlands 3
    2801, // Ny'alotha, the Waking City
    2816, // Delete me please
    2818, // Lordaeron Garrison
    2820, // Eastern Kingdoms - Copy
    2821, // Bilge Rat Corsair A
    2822, // Bilge Rat Corsair B
    2823, // Bilge Rat Corsair C
    2829, // The Dauntless
    2834, // 11.1 Warband - General
    2837, // 11.1 Warband - Delve Select Screen - Nightfall Sanctum
    2847, // 11.1 Warband - Freywold
    2851, // 11.1 Warband - The Gallagio
    2857, // Scarlet Halls
    2858, // 12.0 Quel'Danas Scenario
    2860, // Blood Elf Frigate (Scenario)
    2872, // Undermine
    2916, // Vaults of Atal'Utek
    2927, // Arathi Highlands RPE
    2954, // 11.2 Warband - K'aresh
    2982, // DELETE ME
    2984, // 12.0.0 Transport: Ethereal Skiff
    3007, // The Escape from Durnholde - Lorewalking
    3019, // 12.0 Quel'Danas Intro Scenario Ship Map
    3026, // 12.0 Warband - Founder's Point
    3027, // 12.0 Warband - Razorwind Shores
    3040, // Null Space
    3047, // Val
    3053, // 12.1 Warband - Silvermoon
    3075, // Naigtal
    3099, // 12.1 Warband - Silvermoon - Void
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn table_is_sorted_by_map_id() {
        assert!(TABLE.windows(2).all(|w| w[0] < w[1]));
    }

    #[test]
    fn continents_are_open_world_and_instances_are_not() {
        // Eastern Kingdoms (Silvermoon's map) and Kalimdor are open
        // world; a tripwire against the column changing meaning.
        assert!(open_world(0) && open_world(1));
        assert!(!TABLE.contains(&u32::MAX));
    }
}
