//! GENERATED by tools/gen-proc-spells.sh — do not edit by hand.
//! Source: local client DB2s via wowdps-extract, build 12.1.0.69933.
//! 16 procs under 15 drivers.
//!
//! Maps a talent proc's combat-log spell id to the spell that drives it, by
//! the driver's name as the log writes it, so the ability tree hangs the proc
//! under its driver (CONTRACT.md R26). Membership is curated in
//! tools/extract/src/procgen.rs; every entry is tied to its driver by the
//! client's own text or effects and shown in real logs, and that evidence
//! sits in proc_spells.expected.md.

/// The name of the spell that drives a proc, or `None` for a spell the table
/// does not curate.
pub(crate) fn driver_of(spell_id: u32) -> Option<&'static str> {
    let i = TABLE.binary_search_by_key(&spell_id, |e| e.0).ok()?;
    let &(_, d) = TABLE.get(i)?;
    DRIVERS.get(d as usize).copied()
}

/// The drivers, sorted.
static DRIVERS: &[&str] = &[
    "Blade of Justice",
    "Chain Lightning",
    "Dread Plague",
    "Dreadbite",
    "Elemental Blast",
    "Execute",
    "Fury of Elune",
    "Holy Shock",
    "Lava Burst",
    "Lightning Bolt",
    "Shadow Word: Madness",
    "Shadowy Apparition",
    "Virulent Plague",
    "Wake of Ashes",
    "Wither",
];

/// (proc id, index into DRIVERS), sorted by proc id.
#[rustfmt::skip]
static TABLE: &[(u32, u16)] = &[
    (45284,9), (45297,1), (120588,4), (285466,8), (383346,0), (383706,5),
    (403695,13), (428682,6), (445736,14), (461499,7), (1231479,11), (1241167,12),
    (1241171,2), (1261160,0), (1264176,10), (1276960,3),
];

#[cfg(test)]
mod tests {
    /// Strictly ascending: binary search demands it, and it doubles as
    /// a dedup check.
    #[test]
    fn table_is_sorted_by_spell_id() {
        assert!(super::TABLE.windows(2).all(|w| w[0].0 < w[1].0));
    }

    /// Every entry names a driver, and a stranger is `None`.
    #[test]
    fn every_entry_resolves() {
        assert!(super::TABLE.iter().all(|e| super::driver_of(e.0).is_some()));
        assert_eq!(super::driver_of(0), None);
    }
}
