//! GENERATED by tools/gen-role-spells.sh — do not edit by hand.
//! Source: local client DB2s via wowdps-extract, build 12.1.0.69875.
//! 138 role spells.
//!
//! Maps a combat-log aura id to the role its buff plays — active mitigation,
//! a defensive, an external, a support buff, an offensive cooldown or a
//! healing cooldown — so
//! the meter can open a span on the buff's target with its caster
//! (CONTRACT.md R18). Membership is curated in tools/extract/src/rolegen.rs;
//! every entry's name and APPLY_AURA effect are proven against the client,
//! and its real-log census sits in role_spells.expected.md.

use wowdps_model::RoleSpellKind;

/// The role a buff plays, or `None` for a spell the table does not curate.
#[allow(dead_code)] // consumed by the meter's R18 spans (4a-ii)
pub(crate) fn role_kind(spell_id: u32) -> Option<RoleSpellKind> {
    let i = TABLE.binary_search_by_key(&spell_id, |e| e.0).ok()?;
    let &(_, code) = TABLE.get(i)?;
    KINDS.get(code as usize).copied()
}

const KINDS: [RoleSpellKind; 6] = [
    RoleSpellKind::ActiveMitigation,
    RoleSpellKind::Defensive,
    RoleSpellKind::External,
    RoleSpellKind::SupportBuff,
    RoleSpellKind::Cooldown,
    RoleSpellKind::HealingCooldown,
];

/// (aura id, kind code), sorted by aura id.
#[rustfmt::skip]
static TABLE: &[(u32, u8)] = &[
    (498,1), (642,1), (740,5), (871,1), (1022,2), (1719,4), (1966,1), (2825,2),
    (5277,1), (6940,2), (10060,2), (11426,1), (12472,4), (12975,1), (13750,4), (15286,5),
    (19236,1), (19574,4), (22812,1), (22842,1), (23920,1), (29166,2), (31224,1), (31821,1),
    (31850,1), (31884,4), (32182,2), (33206,2), (33891,5), (42650,4), (45438,1), (47536,5),
    (47585,1), (47788,2), (48707,1), (48792,1), (49039,1), (51271,4), (55233,1), (55342,1),
    (61336,1), (64843,5), (77535,0), (80353,2), (81256,1), (81782,1), (86659,1), (90355,2),
    (97463,1), (102342,2), (102543,4), (102558,4), (102560,4), (104773,1), (106951,4), (107574,4),
    (108271,1), (108280,5), (108416,1), (110960,1), (111685,4), (114051,4), (114052,5), (115176,1),
    (116849,2), (118038,1), (120954,1), (121471,4), (122278,1), (122470,1), (122783,1), (132403,0),
    (132404,0), (137639,4), (145629,1), (160452,2), (162264,4), (184364,1), (184662,1), (185311,1),
    (185422,4), (186265,1), (187827,1), (190319,4), (192081,0), (194223,4), (194249,4), (195181,0),
    (196555,1), (200183,5), (203819,0), (204018,2), (205180,4), (207289,4), (207771,1), (212800,1),
    (215479,0), (216331,5), (235313,1), (235450,1), (263648,1), (264667,2), (264735,1), (265187,4),
    (274837,4), (288613,4), (322507,1), (325174,1), (342246,1), (357170,2), (359844,4), (360952,4),
    (363916,1), (365362,4), (370667,2), (374227,1), (374349,1), (375087,4), (389539,1), (390386,2),
    (391109,4), (391528,4), (395152,3), (403876,1), (410089,3), (413984,3), (421453,5), (442204,4),
    (442726,4), (446035,4), (466904,2), (472433,5), (1219480,4), (1225789,4), (1235391,4), (1249658,4),
    (1269349,4), (1277482,2),
];

#[cfg(test)]
mod tests {
    /// Strictly ascending: binary search demands it, and it doubles as
    /// a dedup check.
    #[test]
    fn table_is_sorted_by_spell_id() {
        assert!(super::TABLE.windows(2).all(|w| w[0].0 < w[1].0));
    }

    /// Every code in the table names a kind, and a stranger is `None`.
    #[test]
    fn every_entry_resolves() {
        assert!(super::TABLE.iter().all(|e| super::role_kind(e.0).is_some()));
        assert_eq!(super::role_kind(0), None);
    }
}
