//! GENERATED by tools/gen-role-spells.sh — do not edit by hand.
//! Source: local client DB2s via wowdps-extract, build 12.1.0.69587.
//! 64 role spells.
//!
//! Maps a combat-log aura id to the role its buff plays — active mitigation,
//! a defensive, an external, a support buff or an offensive cooldown — so
//! the meter can open a span on the buff's target with its caster
//! (CONTRACT.md R18). Membership is curated in tools/extract/src/rolegen.rs;
//! every entry's name and APPLY_AURA effect are proven against the client,
//! and its real-log census sits in role_spells.expected.md.

use wowdps_model::RoleSpellKind;

/// The role a buff plays, or `None` for a spell the table does not curate.
#[allow(dead_code)] // consumed by the meter's R18 spans (4a-ii)
pub(crate) fn role_kind(spell_id: u32) -> Option<RoleSpellKind> {
    let i = TABLE.binary_search_by_key(&spell_id, |e| e.0).ok()?;
    let &(_, code) = TABLE.get(i)?;
    KINDS.get(code as usize).copied()
}

const KINDS: [RoleSpellKind; 5] = [
    RoleSpellKind::ActiveMitigation,
    RoleSpellKind::Defensive,
    RoleSpellKind::External,
    RoleSpellKind::SupportBuff,
    RoleSpellKind::Cooldown,
];

/// (aura id, kind code), sorted by aura id.
#[rustfmt::skip]
static TABLE: &[(u32, u8)] = &[
    (871,1), (1022,2), (1719,4), (2825,2), (5277,1), (6940,2), (10060,2), (19574,4),
    (29166,2), (31821,1), (31884,4), (32182,2), (33206,2), (42650,4), (47585,1), (47788,2),
    (48792,1), (51271,4), (61336,1), (77535,0), (80353,2), (81256,1), (86659,1), (90355,2),
    (97463,1), (102342,2), (102560,4), (104773,1), (107574,4), (108271,1), (114051,4), (114052,4),
    (116849,2), (120954,1), (121471,4), (132403,0), (132404,0), (145629,1), (160452,2), (162264,4),
    (186265,1), (190319,4), (192081,0), (194249,4), (195181,0), (203819,0), (212800,1), (215479,0),
    (264667,2), (274837,4), (288613,4), (325174,1), (342246,1), (357170,2), (363916,1), (365362,4),
    (370667,2), (375087,4), (390386,2), (395152,3), (410089,3), (413984,3), (446035,4), (466904,2),
];

#[cfg(test)]
mod tests {
    /// Strictly ascending: binary search demands it, and it doubles as
    /// a dedup check.
    #[test]
    fn table_is_sorted_by_spell_id() {
        assert!(super::TABLE.windows(2).all(|w| w[0].0 < w[1].0));
    }

    /// Every code in the table names a kind, and a stranger is `None`.
    #[test]
    fn every_entry_resolves() {
        assert!(super::TABLE.iter().all(|e| super::role_kind(e.0).is_some()));
        assert_eq!(super::role_kind(0), None);
    }
}
